import "dotenv-safe/config.js";

import { fileURLToPath } from "node:url";

import pino from "pino";

import { createGitLabClient } from "@vorth/gitlab-client";
import { postMrNote, updateFixMrUrl } from "@vorth/mcp-tools";
import { changeSurfaceSchema, experimentResultListSchema, hypothesisListSchema, webhookPayloadSchema } from "@vorth/shared-types";

import { generateFixPatch } from "./claude-fix.js";
import { applyPatch, createFixBranch, openDraftMR } from "./gitlab-mr.js";

const logger = pino({ name: "vorth-fix-writer" });

async function safeFailureComment(projectId: number, mrId: number, error: unknown) {
  try {
    await postMrNote(
      createGitLabClient(),
      projectId,
      mrId,
      `Vorth could not generate an automated fix MR.\n\n\`${error instanceof Error ? error.message : "Unknown error"}\``,
    );
  } catch (commentError) {
    logger.error({ err: commentError }, "failed to post fallback fix-writer comment");
  }
}

export async function runFixWriter(input: {
  payload: unknown;
  changeSurface: unknown;
  hypotheses: unknown;
  results: unknown;
  narrative: string;
}) {
  const payload = webhookPayloadSchema.parse(input.payload);
  const changeSurface = changeSurfaceSchema.parse(input.changeSurface);
  const hypotheses = hypothesisListSchema.parse(input.hypotheses);
  const results = experimentResultListSchema.parse(input.results);
  const mr = payload.merge_request ?? payload.object_attributes;

  if (!mr?.iid || !mr.source_branch) {
    throw new Error("Merge request source branch information is missing from the webhook payload.");
  }

  const failedResults = results.filter((result) => !result.passed);
  if (failedResults.length === 0) {
    return { fixMrUrl: undefined };
  }

  try {
    const branch = await createFixBranch(payload.project.id, mr.source_branch, mr.iid);

    for (const result of failedResults) {
      const hypothesis = hypotheses.find((item) => item.id === result.hypothesisId);
      if (!hypothesis) {
        continue;
      }

      const targetFile =
        changeSurface.changedFiles.find((file) => file.includes(hypothesis.targetService)) ??
        changeSurface.changedFiles[0];

      if (!targetFile) {
        continue;
      }

      const source = await createGitLabClient()
        .request(
          `projects/${payload.project.id}/repository/files/${encodeURIComponent(targetFile)}?ref=${encodeURIComponent(mr.source_branch)}`,
        )
        .then((file) =>
          Buffer.from(
            typeof file === "object" && file && "content" in file ? String((file as { content?: string }).content ?? "") : "",
            "base64",
          ).toString("utf8"),
        );

      const patch = await generateFixPatch({
        filePath: targetFile,
        source,
        hypothesis,
        result,
        analysis: input.narrative,
      });

      await applyPatch(payload.project.id, branch, mr.source_branch, patch);
    }

    const draftMr = await openDraftMR(payload.project.id, branch, mr.source_branch, {
      mrId: mr.iid,
      summary: `Automated resilience improvements generated by Vorth for MR #${mr.iid}.\n\n${input.narrative}`,
    });

    if (draftMr.web_url) {
      await updateFixMrUrl(payload.project.id, mr.iid, draftMr.web_url);
      await postMrNote(
        createGitLabClient(),
        payload.project.id,
        mr.iid,
        `Vorth opened a draft fix MR for the failed resilience experiments: ${draftMr.web_url}`,
      );
    }

    return {
      fixMrUrl: draftMr.web_url,
      branch,
    };
  } catch (error) {
    logger.error({ err: error, projectId: payload.project.id, mrId: mr.iid }, "fix writer failed");
    await safeFailureComment(payload.project.id, mr.iid, error);
    throw error;
  }
}

async function readStdin() {
  const chunks: Buffer[] = [];

  for await (const chunk of process.stdin) {
    chunks.push(Buffer.from(chunk));
  }

  return Buffer.concat(chunks).toString("utf8");
}

async function main() {
  const raw = await readStdin();
  const payload = JSON.parse(raw || "{}") as {
    payload: unknown;
    changeSurface: unknown;
    hypotheses: unknown;
    results: unknown;
    narrative: string;
  };
  const result = await runFixWriter(payload);
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((error) => {
    logger.error({ err: error }, "fatal fix writer error");
    process.exitCode = 1;
  });
}
